### ISSUE TITLE
Inference speed is slow

### ISSUE THREAD

**Issue by diaodeyi** [sunshineatnoon/PytorchWCT#27]
Hi , Thanks for your code. The inference time is too long. I think it's unreasonable.

**Comment by sunshineatnoon** [comment]
Most likely the slow inference is caused by SVG decomposition, you can try [AdaIn](https://arxiv.org/abs/1703.06868) or [LST](https://openaccess.thecvf.com/content_CVPR_2019/papers/Li_Learning_Linear_Transformations_for_Fast_Image_and_Video_Style_Transfer_CVPR_2019_paper.pdf) if you need faster style transfer algorithm.
